version: '3'

volumes:
  media: {}
  static: {}

services:
  postgres:
    image: postgres:10.5
    env_file:
      - ./config/db/dev.env
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0.9      

  app: &app
    build:
      context: .
    image: anopa/adminsmart_django:latest
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app
      - static:/app/adminsmart/static
      - media:/app/adminsmart/media
    env_file:
      - ./config/db/dev.env
      - ./config/django/dev.env
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    command: /start-app-dev.sh

  celeryworker:
    <<: *app
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celery-worker.sh

  celerybeat:
    <<: *app
    user: root
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celery-beat.sh