version: '3'

volumes:
  media: {}
  static: {}

services:
  postgres:
    image: postgres:10.5
    env_file:
      - config.env
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0.9

  api: &api
    build:
      context: .
    image: anopa/adminsmart_django:latest
    depends_on:
      - postgres
    volumes:
      - ./api:/api
      - static:/api/static
      - media:/api/media
    env_file:
      - config.env
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    command: /start-api-dev.sh

  celeryworker:
    <<: *api
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celery-worker.sh

  celerybeat:
    <<: *api
    user: root
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celery-beat.sh

  flower:
    <<: *api
    ports:
      - "5555:5555"
    command: /start-celery-flower.sh
